name: salud_dominicana
description: Asegurarndo la salud de tus seres amados.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^1.2.6

  #good for mocks
  mockito: ^4.1.4

  #hooks makes your life easier by removing boileplate
  flutter_bloc: ^6.1.2
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.4

  #riverpod to handle state
  flutter_riverpod: ^0.12.4

  #code generator for unions and data classes
  freezed_annotation: ^0.12.0

  #serialization
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1

  #much better logs
  logger: ^0.9.4

  #styling views in a more css way
  division: ^0.8.8

  #adds snackbar to the project
  flash: ^1.3.2

  #route generator
  auto_route: ^0.6.9

  #picker
  image_picker: ^0.6.7+22

  # store image
  path_provider: ^1.6.27

  # store & load data
  shared_preferences: ^0.5.12+4

  # generate ids mostly for testing
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linters
  pedantic: ^1.10.0
  very_good_analysis: ^1.0.4

  #code generator
  build_runner: ^1.11.1
  freezed: ^0.12.7
  auto_route_generator: ^0.6.10

flutter:
  uses-material-design: true
