name: salud_dominicana
description: Asegurarndo la salud de tus seres amados.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  mockito: ^4.1.4
  flutter_bloc: ^6.1.1
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.3+1
  flutter_riverpod: ^0.12.3+1
  freezed_annotation: ^0.12.0
  intl: ^0.16.1
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  meta: ^1.1.8
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  build_runner: ^1.11.1
  freezed: ^0.12.7
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
