name: salud_dominicana
description: Asegurarndo la salud de tus seres amados.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.0-nullsafety.3

  #animations
  animations: ^2.0.0-nullsafety.0

  #handle splash for native android and ios projects
  flutter_native_splash: ^0.3.0

  #simple network requests (retrofit)
  #chopper: ^3.0.6 - not null safety yet

  #to check internet connecion
  #connectivity: ^2.0.2

  #good for mocks
  mockito: ^5.0.0-nullsafety.7

  #hooks makes your life easier by shrinking boileplate
  flutter_bloc: ^7.0.0-nullsafety.2
  flutter_hooks: ^0.16.0-nullsafety.0
  hooks_riverpod: ^0.13.0-nullsafety.3

  #riverpod to handle state
  flutter_riverpod: ^0.13.0-nullsafety.3

  #code generator for unions and data classes
  freezed_annotation: ^0.13.0-nullsafety.0

  #serialization
  json_annotation: ^4.0.0

  #much better logs
  logger: ^1.0.0-nullsafety.0

  #styling views in a more css way
  division: ^0.8.8

  #adds snackbar to the project
  flash: ^1.4.0-nullsafety

  #route generator
  auto_route: ^0.6.9

  #picker
  image_picker: ^0.7.0-nullsafety

  # store image
  path_provider: ^2.0.0-nullsafety

  # store & load data
  shared_preferences: ^2.0.0-nullsafety

  # generate ids mostly for testing
  #uuid: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/localize/en.json
    - lib/Assets/localize/es.json
    - lib/Assets/images/application_icons/demo-icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generates android and IOS icons
  flutter_launcher_icons: ^0.8.1

 #Serialization
  json_serializable: ^4.0.0

  # linters
  pedantic: ^1.10.0
  very_good_analysis: ^2.0.0-nullsafety.0

  #code generator
  build_runner: ^1.11.1
  freezed: ^0.13.0-nullsafety.2
  auto_route_generator: ^0.6.10
  #chopper_generator: ^3.0.6 - not null-safety

